#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

autoload -Uz promptinit
promptinit
prompt parnell

autoload colors; colors;

export PATH=${HOME}/.cabal/bin:$PATH
export PATH=${HOME}/Programming/android-studio/bin:$PATH

export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-amd64

LS_COLORS="di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=01;05;37;41:mi=01;05;37;41:su=37;41:sg=30;43:tw=30;42:ow=34;42:st=37;44:ex=01;32";
LSCOLORS="ExGxFxDxCxDxDxhbhdacEc";

export LS_COLORS=$LS_COLORS

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alhF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Use same colors for autocompletion
zmodload -a colors
zmodload -a autocomplete
zmodload -a complist
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# Alias to reload ZSH config when changed
alias reload=". ~/.zshrc && echo 'ZSH config reloaded from ~/.zshrc'"
alias ec=emacsclient
alias rm="trash-rm"

# Make an org-protocol alias
alias todo="/usr/bin/emacsclient org-protocol:/capture:/t/TODO"

# The next line updates PATH for the Google Cloud SDK.
source /home/parnell/.google-cloud-sdk/path.zsh.inc

# The next line enables bash completion for gcloud.
source /home/parnell/.google-cloud-sdk/completion.zsh.inc

# Export Plum's AWS keys
export AWS_ACCESS_KEY=AKIAJ4KCBA2KKHJQN5TQ
export AWS_SECRET_KEY=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

# Activate virtualenvwrapper
export WORKON_HOME=/media/parnell/Tardis/.venvs
source /usr/local/bin/virtualenvwrapper.sh

# Setup zsh-autosuggestions
# source ~/.zsh-autosuggestions/autosuggestions.zsh

# # Enable autosuggestions automatically
# zle-line-init() {
#     zle autosuggest-start
# }
# zle -N zle-line-init

# # use ctrl+t to toggle autosuggestions(hopefully this wont be needed as
# # zsh-autosuggestions is designed to be unobtrusive)
# bindkey '^T' autosuggest-toggle

# export AUTOSUGGESTION_HIGHLIGHT_COLOR='fg=85, 85, 255'
